print('What are your names?')
student1 = input()
student2 = input()
student3 = input()
student4 = input()
print('What are your GPAs?')
gpa1 = input()
gpa2 = input()
gpa3 = input()
gpa4 = input()
x = ((gpa1 + gpa2 + gpa3 + gpa4)/4)
print('Thank you', student1 , student2 , student3 , student4 , 'The average of your GPAs is' , x )
